import { Theme } from '@/types';

export const THEMES: Theme[] = [
  {
    key: 'crystal-white',
    nameEn: 'Crystal Clear White',
    nameUr: 'صاف کرسٹل',
    nameAr: 'بلوري أبيض',
    bgClass: 'bg-crystal',
    themeClass: 'theme-crystal-white',
    gradientFrom: '#e0f2fe',
    gradientTo: '#f0f9ff',
    accentColor: '#1e40af',
    previewGradient: 'linear-gradient(135deg, #e0f2fe, #f0f9ff, #e8f5fe)',
    isDark: false,
  },
  {
    key: 'emerald',
    nameEn: 'Emerald Green',
    nameUr: 'زمرد سبز',
    nameAr: 'زمردي أخضر',
    bgClass: 'bg-emerald-glass',
    themeClass: 'theme-emerald',
    gradientFrom: '#d1fae5',
    gradientTo: '#ecfdf5',
    accentColor: '#065f46',
    previewGradient: 'linear-gradient(135deg, #6ee7b7, #d1fae5, #a7f3d0)',
    isDark: false,
  },
  {
    key: 'crimson',
    nameEn: 'Crimson Gold',
    nameUr: 'سرخ سونا',
    nameAr: 'قرمزي ذهبي',
    bgClass: 'bg-crimson-glass',
    themeClass: 'theme-crimson',
    gradientFrom: '#fee2e2',
    gradientTo: '#fff1f2',
    accentColor: '#991b1b',
    previewGradient: 'linear-gradient(135deg, #fca5a5, #fecaca, #fde8e8)',
    isDark: false,
  },
  {
    key: 'royal-blue',
    nameEn: 'Royal Blue',
    nameUr: 'شاہی نیلا',
    nameAr: 'أزرق ملكي',
    bgClass: 'bg-royal-glass',
    themeClass: 'theme-royal-blue',
    gradientFrom: '#dbeafe',
    gradientTo: '#eff6ff',
    accentColor: '#1e3a8a',
    previewGradient: 'linear-gradient(135deg, #93c5fd, #bfdbfe, #dbeafe)',
    isDark: false,
  },
  {
    key: 'golden-mosque',
    nameEn: 'Golden Mosque',
    nameUr: 'سونے کی مسجد',
    nameAr: 'مسجد ذهبية',
    bgClass: 'bg-golden-glass',
    themeClass: 'theme-golden-mosque',
    gradientFrom: '#fef3c7',
    gradientTo: '#fffbeb',
    accentColor: '#92400e',
    previewGradient: 'linear-gradient(135deg, #fcd34d, #fde68a, #fef3c7)',
    isDark: false,
  },
  {
    key: 'pakistan-green',
    nameEn: 'Pakistan Green & White',
    nameUr: 'پاکستانی سبز',
    nameAr: 'أخضر باكستاني',
    bgClass: 'bg-emerald-glass',
    themeClass: 'theme-pakistan-green',
    gradientFrom: '#dcfce7',
    gradientTo: '#f0fdf4',
    accentColor: '#14532d',
    previewGradient: 'linear-gradient(135deg, #4ade80, #86efac, #dcfce7)',
    isDark: false,
  },
  {
    key: 'holographic',
    nameEn: 'Holographic Crystal',
    nameUr: 'ہولوگرافک کرسٹل',
    nameAr: 'هولوغرافي',
    bgClass: '',
    themeClass: 'theme-holographic',
    gradientFrom: '#ede9fe',
    gradientTo: '#f5f3ff',
    accentColor: '#6d28d9',
    previewGradient: 'linear-gradient(135deg, #c4b5fd, #a5b4fc, #93c5fd, #6ee7b7)',
    isDark: false,
  },
  {
    key: 'sunset',
    nameEn: 'Sunset Orange',
    nameUr: 'غروب کا نارنجی',
    nameAr: 'غروب برتقالي',
    bgClass: '',
    themeClass: 'theme-sunset',
    gradientFrom: '#ffedd5',
    gradientTo: '#fff7ed',
    accentColor: '#9a3412',
    previewGradient: 'linear-gradient(135deg, #fb923c, #fca5a1, #fed7aa)',
    isDark: false,
  },
];
